In [1]:
import pandas as pd
import requests
import numpy as np
from lightweight_charts import Chart
from stock_indicators import indicators, Quote
from datetime import datetime, timedelta
import asyncio
import nest_asyncio

nest_asyncio.apply()

In [2]:
import yfinance as yf
df = yf.download('SPXL', start='2010-01-01', multi_level_index=False)
df.reset_index(inplace=True)
df.to_csv('SPXL.csv', index=False)
df = pd.read_csv('SPXL.csv')
rawdf = df.copy()
df['Date'] = pd.to_datetime(df['Date'])
df.head()

C:\Users\jwang\AppData\Local\Temp\ipykernel_8184\2805507071.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download('SPXL', start='2010-01-01', multi_level_index=False)
[*********************100%***********************]  1 of 1 completed

        Date     Close      High       Low      Open    Volume
0 2010-01-04  4.081053  4.087707  3.983462  3.984201  28238400
1 2010-01-05  4.119499  4.121717  4.029303  4.076619  33206400
2 2010-01-06  4.130588  4.157204  4.098059  4.107670  44194800
3 2010-01-07  4.179384  4.192691  4.069225  4.109149  43773600
4 2010-01-08  4.223743  4.228919  4.119499  4.143158  39685200

In [3]:
import yfinance as yf
df = yf.download('SPXL', start='2010-01-01', multi_level_index=False)
df.reset_index(inplace=True)
df.to_csv('SPXL.csv', index=False)
df = pd.read_csv('SPXL.csv')
rawdf = df.copy()
df['Date'] = pd.to_datetime(df['Date'])
df.head()

C:\Users\jwang\AppData\Local\Temp\ipykernel_8184\2805507071.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download('SPXL', start='2010-01-01', multi_level_index=False)
[*********************100%***********************]  1 of 1 completed

        Date     Close      High       Low      Open    Volume
0 2010-01-04  4.081053  4.087707  3.983462  3.984201  28238400
1 2010-01-05  4.119499  4.121717  4.029303  4.076619  33206400
2 2010-01-06  4.130588  4.157204  4.098059  4.107670  44194800
3 2010-01-07  4.179384  4.192691  4.069225  4.109149  43773600
4 2010-01-08  4.223743  4.228919  4.119499  4.143158  39685200

In [4]:
quotes = [
    Quote(d, o, h, l, c, v)
    for d, o, h, l, c, v in zip(
        df['Date'],
        df['Open'],
        df['High'],
        df['Low'],
        df['Close'],
        df['Volume']
    )
]

In [5]:
from lightweight_charts import Chart


def on_search(chart, string):
    print(f'Search Text: "{string}" | Chart/SubChart ID: "{chart.id}"')
    
    
if __name__ == '__main__':
    chart = Chart()
    
    # Subscribe the function above to search event
    chart.events.search += on_search  
    
    chart.show(block=True)

In [6]:
from lightweight_charts import Chart

def on_button_press(chart):
    new_button_value = 'On' if chart.topbar['my_button'].value == 'Off' else 'Off'
    chart.topbar['my_button'].set(new_button_value)
    print(f'Turned something {new_button_value.lower()}.')
    
    
if __name__ == '__main__':
    chart = Chart()
    chart.topbar.button('my_button', 'Off', func=on_button_press)
    chart.show(block=True)

In [7]:
from lightweight_charts import Chart

def on_timeframe_selection(chart):
    print(f'Getting data with a {chart.topbar["my_switcher"].value} timeframe.')
    
    
if __name__ == '__main__':
    chart = Chart()
    chart.topbar.switcher(
        name='my_switcher',
        options=('1min', '5min', '30min'),
        default='5min',
        func=on_timeframe_selection)
    chart.show(block=True)

In [8]:
# import asyncio
# from datetime import datetime
# from lightweight_charts import Chart


# async def update_clock(chart):
#     while chart.is_alive:
#         await asyncio.sleep(1-(datetime.now().microsecond/1_000_000))
#         chart.topbar['clock'].set(datetime.now().strftime('%H:%M:%S'))


# async def main():
#     chart = Chart()
#     chart.topbar.textbox('clock')
#     await asyncio.gather(chart.show_async(), update_clock(chart))


# if __name__ == '__main__':
#     asyncio.run(main())

In [9]:
# import asyncio
# import pandas as pd
# from lightweight_charts import Chart


# async def data_loop(chart):
#     ticks = pd.read_csv('SPXL.csv')
    
#     for i, tick in ticks.iterrows():
#         if not chart.is_alive:
#             return
#         chart.update_from_tick(ticks.iloc[i])
#         await asyncio.sleep(0.03)
        
        
# def on_new_bar(chart):
#     print('New bar event!')
    
    
# def on_timeframe_selection(chart):
#     print(f'Selected timeframe of {chart.topbar["timeframe"].value}')


# async def main():
#     chart = Chart()
#     chart.events.new_bar += on_new_bar
    
#     chart.topbar.switcher('timeframe', ('1min', '5min'), func=on_timeframe_selection)
    
#     df = pd.read_csv('SPXL.csv')
    
#     chart.set(df)
#     await asyncio.gather(chart.show_async(), data_loop(chart))
    

# if __name__ == '__main__':
#     asyncio.run(main())

In [10]:
# import pandas as pd
# from lightweight_charts import Chart

# def on_row_click(row):
#     row['PL'] = round(row['PL']+1, 2)
#     row.background_color('PL', 'green' if row['PL'] > 0 else 'red')

#     table.footer[1] = row['Ticker']

# if __name__ == '__main__':
#     chart = Chart(width=1000, inner_width=0.7, inner_height=1)
#     subchart = chart.create_subchart(width=0.3, height=0.5)
#     df = pd.read_csv('SPXL.csv')
#     chart.set(df)
#     subchart.set(df)

#     table = chart.create_table(width=0.3, height=0.2,
#                   headings=('Ticker', 'Quantity', 'Status', '%', 'PL'),
#                   widths=(0.2, 0.1, 0.2, 0.2, 0.3),
#                   alignments=('center', 'center', 'right', 'right', 'right'),
#                   position='left', func=on_row_click)

#     table.format('PL', f'£ {table.VALUE}')
#     table.format('%', f'{table.VALUE} %')

#     table.new_row('SPY', 3, 'Submitted', 0, 0)
#     table.new_row('AMD', 1, 'Filled', 25.5, 105.24)
#     table.new_row('NVDA', 2, 'Filled', -0.5, -8.24)

#     table.footer(2)
#     table.footer[0] = 'Selected:'

#     chart.show(block=True)

In [11]:
# import pandas as pd
# from lightweight_charts import Chart


# def get_bar_data(symbol, timeframe):
#     if symbol not in ('AAPL', 'GOOGL', 'TSLA'):
#         print(f'No data for "{symbol}"')
#         return pd.DataFrame()
#     return pd.read_csv(f'bar_data/{symbol}_{timeframe}.csv')


# def on_search(chart, searched_string):
#     new_data = get_bar_data(searched_string, chart.topbar['timeframe'].value)
#     if new_data.empty:
#         return
#     chart.topbar['symbol'].set(searched_string)
#     chart.set(new_data)
    
#     # Load the drawings saved under the symbol.
#     chart.toolbox.load_drawings(searched_string)


# def on_timeframe_selection(chart):
#     new_data = get_bar_data(chart.topbar['symbol'].value, chart.topbar['timeframe'].value)
#     if new_data.empty:
#         return
#     # The symbol has not changed, so we want to re-render the drawings.
#     chart.set(new_data, keep_drawings=True)


# if __name__ == '__main__':
#     chart = Chart(toolbox=True)
#     chart.legend(True)

#     chart.events.search += on_search
#     chart.topbar.textbox('symbol', 'TSLA')
#     chart.topbar.switcher(
#         'timeframe',
#         ('1min', '5min', '30min'),
#         default='5min',
#         func=on_timeframe_selection
#     )

#     df = get_bar_data('TSLA', '5min')

#     chart.set(df)

#     # Imports the drawings saved in the JSON file.
#     chart.toolbox.import_drawings('drawings.json')
    
#     # Loads the drawings under the default symbol.
#     chart.toolbox.load_drawings(chart.topbar['symbol'].value)  
    
#     # Saves drawings based on the symbol.
#     chart.toolbox.save_drawings_under(chart.topbar['symbol'])  

#     chart.show(block=True)
    
#     # Exports the drawings to the JSON file upon close.
#     chart.toolbox.export_drawings('drawings.json')

In [12]:
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(inner_width=0.5, inner_height=0.5)
    chart2 = chart.create_subchart(position='right', width=0.5, height=0.5)
    chart3 = chart.create_subchart(position='left', width=0.5, height=0.5)
    chart4 = chart.create_subchart(position='right', width=0.5, height=0.5)

    chart.watermark('1')
    chart2.watermark('2')
    chart3.watermark('3')
    chart4.watermark('4')

    df = pd.read_csv('SPXL.csv')
    chart.set(df)
    chart2.set(df)
    chart3.set(df)
    chart4.set(df)

    chart.show(block=True)

In [13]:
# import pandas as pd
# from lightweight_charts import Chart

# if __name__ == '__main__':
#     chart = Chart(inner_width=1, inner_height=0.8)
#     chart.time_scale(visible=False)

#     chart2 = chart.create_subchart(width=1, height=0.2, sync=True)
#     line = chart2.create_line()
    
#     df = pd.read_csv('ohlcv.csv')
#     df2 = pd.read_csv('rsi.csv')

#     chart.set(df)
#     line.set(df2)

#     chart.show(block=True)

In [14]:
import pandas as pd
from lightweight_charts import Chart

# ascii symbols
FULLSCREEN = '■'
CLOSE = '×'


def on_max(target_chart):
    button = target_chart.topbar['max']
    if button.value == CLOSE:
        [c.resize(0.5, 0.5) for c in charts]
        button.set(FULLSCREEN)
    else:
        for chart in charts:
            width, height = (1, 1) if chart == target_chart else (0, 0)
            chart.resize(width, height)
        button.set(CLOSE)


if __name__ == '__main__':
    main_chart = Chart(inner_width=0.5, inner_height=0.5)
    charts = [
        main_chart,
        main_chart.create_subchart(position='top', width=0.5, height=0.5),
        main_chart.create_subchart(position='left', width=0.5, height=0.5),
        main_chart.create_subchart(position='right', width=0.5, height=0.5),
    ]

    df = pd.read_csv('SPXL.csv')
    for i, c in enumerate(charts):
        chart_number = str(i+1)
        c.watermark(chart_number)
        c.topbar.textbox('number', chart_number)
        c.topbar.button('max', FULLSCREEN, False, align='right', func=on_max)
        c.set(df)

    charts[0].show(block=True)

In [15]:
# import datetime as dt
# import yfinance as yf
# from lightweight_charts import Chart


# def get_bar_data(symbol, timeframe):
#     if timeframe in ('1m', '5m', '30m'):
#         days = 7 if timeframe == '1m' else 60
#         start_date = dt.datetime.now()-dt.timedelta(days=days)
#     else:
#         start_date = None

#     chart.spinner(True)
#     data = yf.download(symbol, start_date, interval=timeframe)
#     chart.spinner(False)

#     if data.empty:
#         return False
#     chart.set(data)
#     return True


# def on_search(chart, searched_string):
#     if get_bar_data(searched_string, chart.topbar['timeframe'].value):
#         chart.topbar['symbol'].set(searched_string)


# def on_timeframe_selection(chart):
#     get_bar_data(chart.topbar['symbol'].value, chart.topbar['timeframe'].value)


# if __name__ == '__main__':
#     chart = Chart(toolbox=True, debug=True)
#     chart.legend(True)
#     chart.events.search += on_search
#     chart.topbar.textbox('symbol')
#     chart.topbar.switcher(
#         'timeframe',
#         ('1m', '5m', '30m', '1d', '1wk'),
#         default='5m',
#         func=on_timeframe_selection
#     )

#     chart.show(block=True)

In [16]:
# from lightweight_charts import Chart

# def place_buy_order(key):
#     print(f'Buy {key} shares.')


# def place_sell_order(key):
#     print(f'Sell all shares, because I pressed {key}.')


# if __name__ == '__main__':
#     chart = Chart()
#     chart.hotkey('shift', (1, 2, 3), place_buy_order)
#     chart.hotkey('shift', 'X', place_sell_order)
#     chart.show(block=True)

In [17]:
# import pandas as pd
# from lightweight_charts import Chart


# def get_bar_data(symbol, timeframe):
#     if symbol not in ('AAPL', 'GOOGL', 'TSLA'):
#         print(f'No data for "{symbol}"')
#         return pd.DataFrame()
#     return pd.read_csv(f'bar_data/{symbol}_{timeframe}.csv')


# def on_search(chart, searched_string):
#     new_data = get_bar_data(searched_string, chart.topbar['timeframe'].value)
#     if new_data.empty:
#         return
#     chart.topbar['symbol'].set(searched_string)
#     chart.set(new_data)

    
# def on_timeframe_selection(chart):
#     new_data = get_bar_data(chart.topbar['symbol'].value, chart.topbar['timeframe'].value)
#     if new_data.empty:
#         return
#     chart.set(new_data, True)

    
# def on_horizontal_line_move(chart, line):
#     print(f'Horizontal line moved to: {line.price}')


# if __name__ == '__main__':
#     chart = Chart(toolbox=True)
#     chart.legend(True)
    
#     chart.events.search += on_search

#     chart.topbar.textbox('symbol', 'TSLA')
#     chart.topbar.switcher('timeframe', ('1min', '5min', '30min'), default='5min',
#                           func=on_timeframe_selection)

#     df = get_bar_data('TSLA', '5min')
#     chart.set(df)

#     chart.horizontal_line(200, func=on_horizontal_line_move)

#     chart.show(block=True)

In [18]:
import pandas as pd
from lightweight_charts import JupyterChart

chart = JupyterChart(width=1000, height=400)

df = pd.read_csv('SPXL.csv')
chart.set(df)

chart.load()